### ISSUE TITLE
bundling multiple times for the same file

### ISSUE THREAD

**Issue by pcompassion** [sergei-maertens/django-systemjs#15]
when there are multiple
```{% systemjs_import 'my-app.js' %}```

Log shows my-app is being bundled multiple times.

I think it would be safe to bundle only once for each unique file.

**Comment by sergei-maertens** [comment]
That is indeed the intended behaviour, can you provide some details to
reproduce?

**Comment by pcompassion** [comment]
I have `a.html` which has `{% systemjs_import 'my-app.js' %}`
I also have `b.html` which has  `{% systemjs_import 'my-app.js' %}`

jspm is bundling my-app.js twice even though I think bundling once should be sufficient.

**Comment by sergei-maertens** [comment]
Ah yes, I can see that happening. Did not think of it. I'll add a testcase
and fix asap - won't be before the end of the weekend though.

Thanks for the report!
