### ISSUE TITLE
could use `async` in <script> tag

### ISSUE THREAD

**Issue by pcompassion** [sergei-maertens/django-systemjs#21]
I think most browsers support it.

**Comment by sergei-maertens** [comment]
https://css-tricks.com/async-attribute-scripts-bottom/ - what's keeping you from adding it to the bottom of your page?

**Comment by pcompassion** [comment]
didn't know it was the same thing. I already have them at the bottom. 
I'm having an issue where the same page loads sometimes fast, sometimes slow. 
Just thought it might help.

closing.

**Comment by sergei-maertens** [comment]
Okay

**Comment by pcompassion** [comment]
Hello @sergei-maertens 

I've been hunting down the random slowness. 

I found putting code at the bottom still blocks rendering at least in my android chrome.  
I find commenting the scripts at the bottom of body (about 5 of them) speeds up the perceived page speed.

Hence I could use `async` and `defer` on script tag.

**Comment by sergei-maertens** [comment]
Okay, I'll add the option to specify tag attributes to the template tag - that way you have all freedom and flexibility you need!

**Comment by sergei-maertens** [comment]
@pcompassion - should be released in a few hours during my break, PR here: https://github.com/sergei-maertens/django-systemjs/pull/25. See https://github.com/sergei-maertens/django-systemjs/commit/7723e3ac9e56c9b64fccb9f76ef3a375e323e3b0 for usage

**Comment by sergei-maertens** [comment]
@pcompassion 1.4.1 is available on PyPI
