### ISSUE TITLE
Cannot run in production

### ISSUE THREAD

**Issue by nlhkh** [sergei-maertens/django-systemjs#26]
When in production mode `DEBUG=False`, the static files cannot be found.

**Comment by sergei-maertens** [comment]
Hi @nlhkh,

Did you create the bundles by running `python manage.py systemjs_bundle`?

**Comment by nlhkh** [comment]
Yes, I did. I saw some files generated at “staticfiles/SYSTEMJS/…"

**Comment by sergei-maertens** [comment]
Could you share the `settings.py` (or equivalent) that you are using (with any secrets/password stripped out of course), show your template code and the 404 from the browser debugger?

**Comment by nlhkh** [comment]
Here is my `settings.py`:
```python
"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^th&itckt5w$=yh^%y2il!_^&_#4obpbxd1t%_tkq2_!i7%_#!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'systemjs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'systemjs.finders.SystemFinder',
]
```

And here is the setting I use in production `settings_prod.py`:
```python
from mysite.settings import *

DEBUG = False

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
```

**Comment by sergei-maertens** [comment]
That's looking alright at first sight. Do you mind sharing your `urls.py` as well? And are other static files loading properly, e.g. in the admin?

**Comment by nlhkh** [comment]
Here is my root `urls.py`:
```python
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]
```

And here is my app polls `urls.py`:
```python
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url("foo", views.foo, name="foo"),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]
```

So far my only static files are jspm related.

Now that I think about it. I wonder if Django can server static files in production, because usually we should use NginX or Apache for that. I came from Rails and I am trying out Django.

Let me know what you think.

**Comment by sergei-maertens** [comment]
Yes, the problem is in your urlconfig indeed. In production, you would point your webserver (nginx) at the `settings.STATIC_ROOT`, but for development/local running with `runserver`, you need an extra url to server your staticfiles. This is a confusing topic for many newcomers with Django. I see that I also failed to include them in the example project. This line: https://github.com/modelbrouwers/modelbrouwers/blob/develop/src/brouwers/urls.py#L41 contains what you need, summarized:

```python
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
] + staticfiles_urlpatterns()
```

**Comment by sergei-maertens** [comment]
I've just updated the example project in the `develop` branch, thank you for bringing this to my attention!

**Comment by nlhkh** [comment]
Always happy to help.
I tried to add the `+ staticfiles_urlpatterns()`, but it still does not server the static files.

**Comment by sergei-maertens** [comment]
Just to make sure I have a clear picture - this is not under `runserver`, right, but actually, really in production, with nginx? Can you show me the nginx config file?

**Comment by nlhkh** [comment]
No, this is under `runserver`.

I get your point. I should configure Nginx to serve my files.

**Comment by sergei-maertens** [comment]
No, that's not my point at all, this should properly work in development, as it's how I use it myself as well.

One more question, when using `runserver`, are you using the `settings_prod.py` settings, or the `settings.py`?

**Comment by nlhkh** [comment]
When I use `settings.py` `(DEBUG=True)`, it works.

When I use `settings_prod.py` `(DEBUG=False)`, it does not work.

**Comment by nlhkh** [comment]
I think that when `DEBUG=False`, Django stops serving static files. It only generate urls to static files. I tried adding the extra `+ staticfiles_urlpatterns()` like you mentioned, but I still have the same result. But then I figure that in production, I would not use Django to serve static files anyway, so I wonder if it is worth it to try to make Django serve statics when `DEBUG=False`.

**Comment by sergei-maertens** [comment]
Okay, that confirms my suspicions. For security reasons, the `staticfiles_urlpatterns` does not work with `DEBUG=False`, with the idea that you are running 'really' in production, and thus nginx should serve it. This is sensible.

Now, when using this library, you of course want to test that bundles work correctly in development too. You can do this by keeping `DEBUG=True`, and adding the settings `SYSTEMJS_ENABLED=True` to `settings.py`. By default, the setting `SYSTEMJS_ENABLED` takes the value of `not DEBUG`, but you can make that explicit.

So, to solve your problem: run `runserver` with `settings.py` and add `SYSTEMJS_ENABLED=True` to enable bundle-mode in development.

If you really want to test locally with production settings, you can still do so by adding the staticfiles patterns, even though DEBUG is set to False, like this:

```python
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
] + [
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]
```

Don't forget to remove this again when really going to production, since if you forget to set up nginx correctly as well, Django will now be serving your static files. It will seem as everything is fine, but it will perform bad and it might have security risks.

**Comment by nlhkh** [comment]
I see. This really helps me. I wanted to see how the statics are served in production and you made it very clear. Nice work!

**Comment by sergei-maertens** [comment]
You're welcome, enjoy Django!

**Comment by nlhkh** [comment]
No, this is under `runserver`.

I get your point. I should configure Nginx to serve my files.

**Comment by nlhkh** [comment]
Here is my root `urls.py`:
```python
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]
```

And here is my app polls `urls.py`:
```python
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url("foo", views.foo, name="foo"),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]
```

So far my only static files are jspm related.

Now that I think about it. I wonder if Django can server static files in production, because usually we should use NginX or Apache for that. I came from Rails and I am trying out Django.

Let me know what you think.
