### ISSUE TITLE
Static bundling with Rollup optimization.

### ISSUE THREAD

**Issue by funn** [sergei-maertens/django-systemjs#28]
In jspm 0.17 there is a `jspm build` command that takes similiar to `jspm bundle` command and produces bundle without unused code exports. More info here: http://jspm.io/0.17-beta-guide/static-builds-with-rollup-optimization.html
What are current plans on supporting this?

**Comment by sergei-maertens** [comment]
Currently unsupported, but it looks like a nice feature to have!

How would you like to see the API for this? Something like `{% systemjs_import 'myapp.js' rollup=True %}? Or a global option to pass to the management command, like `python manage.py systemjs_bundle --rollup`?

**Comment by funn** [comment]
As I see it there are two particular uses for `build` command, one is to create optimized bundle for production and the other one is to create static build for using in another projects (passing more options to the cli tool for excluding particular dependency trees). I guess this project should support only the first one and it should be pretty straightforward to implement since the command is similiar to `bundle`, as for the API `python manage.py systemjs_bundle --rollup` seems more sane to me, considering this most usable when creating production bundle.

**Comment by sergei-maertens** [comment]
Sounds relatively straight forward, that can be added. I need to set aside
some time for this though, so if any groundwork could be done with a PR
that would be tremendously appreciated!

**Comment by funn** [comment]
I'd really like to, give me some time for this though.

**Comment by sergei-maertens** [comment]
Of course :)

**Comment by funn** [comment]
That's it. API stays the same, turned out we just fixed sfx build for 0.17 version of jspm.

**Comment by sergei-maertens** [comment]
I see, and at a later point we could ad support for arguments like `--externals` etc?. Cool, I'll try and release a new version to PyPI asap!

**Comment by funn** [comment]
You want `systemjs_bundle` to mimic the corresponding `jspm bundle` or `jspm build` commands with all their flags?

**Comment by sergei-maertens** [comment]
In the long term, yes, it should be able to pass all jspm options to the
management command. For now it's fine.

Thanks for the contribution!

**Comment by funn** [comment]
I think you'll have to split `systemjs_bundle` to two different management commands at some point then. Also I'd like to add `--skip-source-maps` option support to the management command, would you like a PR?

**Comment by sergei-maertens** [comment]
Yeah sure, and you're right, but I'll wait until 0.17 is out of beta to
split it.

**Comment by funn** [comment]
Here is some recent info about 0.17 beta status https://github.com/jspm/jspm-cli/issues/2152#issuecomment-259398840
Seems like they wont change the API in 0.17 anymore

**Comment by sergei-maertens** [comment]
@funn 1.4.2 has just been release to PyPI
